# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  app:
    container_name: dotvotrr
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - API_URL
      - PORT
      - DB_URL
    depends_on:
      - mongo